name: vox_todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

isar_version: &isar_version 3.1.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # DI
  kiwi: ^4.0.1

  # riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1


  # Navigation
  go_router: ^15.1.2

  # Localizations
  easy_localization: ^3.0.7+1

  # UI
  infinite_scroll_pagination: 4.1.0
  flutter_slidable: ^4.0.0

  # Database
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: ^3.0.0
  
  # Code generation
  build_runner: ^2.4.13
  isar_generator: *isar_version
  riverpod_generator: ^2.4.0

  # DI
  kiwi_generator: 4.1.0

  #Logging
  easy_logger: ^0.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/translations/
